pipeline {
    
    agent any

    tools {
        maven "maven"
        //jdk 'open-jdk8'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -Dtest='AppsTest'"
            }
            //post {
            //    always {
            //        junit 'target/surefire-reports/TEST-com.mycompany.app.AppTest.xml'
            //    }
           //} 
        }
            stage('url-check'){
                steps{
                    httpRequest acceptType: 'APPLICATION_JSON', contentType: 'APPLICATION_JSON',
                    httpMode: 'POST', quiet: true,
                    requestBody: '''{
                        "email": "eve.holt@reqres.in",
                        "password": "cityslicka"
            },
            }''',
            url: 'https://reqres.in/api/login'

                }
      }
    }
}
